### ISSUE TITLE
Packages with hyphens don't work

### ISSUE THREAD

**Issue by mbjorge** [colinhoglund/piprepo#2]
I have a package abc-xyz, but this tool strips off the trailing -xyz and only creates an folder & entry for abc.

https://github.com/colinhoglund/piprepo/blob/master/piprepo/utils.py#L7

I wonder why you do the extra .split('-')[0] when PEP503 doesn't have that?

https://www.python.org/dev/peps/pep-0503/#normalized-names

My requirements.txt has:
--extra-index-url http://localhost:8080/simple
abc-xyz==1.0.0

And if I do `python -m SimpleHTTPServer 8080`, I can see that when I try to do a `pip install -r requirements.txt` it tries to "GET /abc-xyz/" but gives a 404 since only /abc/ exists.

**Comment by colinhoglund** [comment]
This is a bug.

I made the incorrect assumption that I could use `-` as a separator between project name and version in downloaded packages, and therefore was getting the project name by using `.split('-')[0]` on file names. I would appear I need to be a bit more deliberate about determining the project name.

**Comment by colinhoglund** [comment]
@mbjorge Thanks for pointing this out. I have created a PR that should address the issue. Would you mind giving it another try when you get a chance?

**Comment by mbjorge** [comment]
Worked like a charm, thanks for the quick fix :)

(and I learned I can install packages diretly from github, so that was neat: `pip install --upgrade https://github.com/colinhoglund/piprepo/tarball/fix_project_naming`)

**Comment by colinhoglund** [comment]
Great, thanks again. I'll merge it and ship it to PyPI.
